### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by daniel-w0** [vulcan-dev/teardown-snippets#1]
- [x]  Add Data Type Boolean back to the snippets
- [x] Add other datatypes such as optional to the Data Types
- [ ] Stop updating because it's good enough
